spring:
  application:
    name: mes-project
  datasource:
    url: ${SPRING_DATASOURCE_URL:${DATABASE_URL:jdbc:postgresql://localhost:5432/mesdb}}
    username: ${SPRING_DATASOURCE_USERNAME:ddu}
    password: ${SPRING_DATASOURCE_PASSWORD:}


  sql:
    init:
      mode: never #always  # 매 실행마다 data.sql 실행

  jpa:
    hibernate:
      ddl-auto: update # Entity 변경시 자동으로 테이블에 반영(데이터유지)
    show-sql: true #실행되는 sql을 콘솔에 출력(개발할때편함)
    defer-datasource-initialization: true  # Hibernate 스키마 생성 후 data.sql 실행
    properties:
      hibernate:
        format_sql: false #개발환경에서만 true

# ──────────────────────────────────────────
# MyBatis 설정
# ──────────────────────────────────────────
mybatis:
  mapper-locations: classpath:mapper/**/*.xml # MyBatis xml파일위치
  type-aliases-package: com.mes.mes_project.dto #DTO 클래스 위치(MyBatis에서 자동 인식)
  configuration:
    map-underscore-to-camel-case: true  # 추가!

# ──────────────────────────────────────────
# JWT 설정
# ──────────────────────────────────────────
jwt:
  secret: ${JWT_SECRET:mes-project-jwt-secret-key-2026-local-dev}
  expiration: 7200000 # 2시간  86400000 #24시간 밀리초

# ──────────────────────────────────────────
# 서버 설정
# ──────────────────────────────────────────
server:
  port: ${PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
